### ISSUE TITLE
Detect Hotwire Native apps?

### ISSUE THREAD

**Issue by ibrahima** [podigee/device_detector#125]
I wonder if it would make sense to detect Hotwire Native apps specifically, just because they might become more common in the Rails world. Right now it gets detected as the mobile browser for that OS (e.g. Safari on iOS) but it would be kinda nice to detect it as something unique. Thanks!

**Comment by benzimmer** [comment]
That should already be possible. Hotwire Native by default adds `Hotwire Native $os` to the user agent string and you can add your of prefix to that as well (all the way at the bottom on [this page](https://native.hotwired.dev/android/configuration#options)). Adding the UA strings for specific apps should happen in the upstream regexes at https://github.com/matomo-org/device-detector. Not sure if I see any value in detecting the generic hotwire UA string mentioned above.
I don't see anything to do in this repo, but I'll leave the issue open for a few more days for visibility.

**Comment by ibrahima** [comment]
Ah I see. I was wondering if there's a way to extend the list for your own purposes (e.g. to detect our own hotwire native application which wouldn't be worth listing in the upstream repo). But I realized it's probably better to just wrap this in our own function that first checks for Hotwire Native and if not falls back to this gem. Thanks though!

**Comment by benzimmer** [comment]
@ibrahima If you're using rails on the backend there's [built-in helpers in turbo-rails](https://github.com/hotwired/turbo-rails/blob/1aa7ba9d38dee1e1b4078a74404131122b907176/app/controllers/turbo/native/navigation.rb#L14) to detect that already.
