### ISSUE TITLE
device_type is nil for UserAgent from Wechat Brower

### ISSUE THREAD

**Issue by hadwinzhy** [podigee/device_detector#24]
the user agent like 

`"Mozilla/5.0 (Linux; Android 5.1; MX5 Build/LMY47I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043015 Safari/537.36 MicroMessenger/6.5.3.980 NetType/4G Language/zh_CN"`

and the device_type is nil

**Comment by yagooar** [comment]
Please present a PR in the upstream repository first: https://github.com/matomo-org/device-detector
Once it gets merged, feel free to open a PR here updating the latest regexes from upstream.
