### ISSUE TITLE
Device Roku returning blank for device name, type , brand, os , version

### ISSUE THREAD

**Issue by akannur** [podigee/device_detector#30]
**Roku UserAgent:**
Mozilla/5.0 (QSP; Roku; UI; 5.3.0.49)

**Comment by yagooar** [comment]
Hello @akannur,

what would be the expected name, type, etc for the device?

**Comment by yagooar** [comment]
Please present a PR in the upstream repo first: https://github.com/matomo-org/device-detector

Once it gets merged, feel free to open a new PR with updated regexes here.
