### ISSUE TITLE
Unable to detect Firefox Android

### ISSUE THREAD

**Issue by Aschen** [podigee/device_detector#33]
Hello,

I have the following user agent : `"Mozilla/5.0 (Android 7.1.2; Mobile; rv:55.0.2) Gecko/55.0.2 Firefox/55.0.2"`

It can't detect that I am using a `smartphone` but it detect that I'm using Android..

```
device = DeviceDetector.new("Mozilla/5.0 (Android 7.1.2; Mobile; rv:55.0.2) Gecko/55.0.2 Firefox/55.0.2")
device.device_type
=> nil
device.os_name
=> "Android"
```

**Comment by yagooar** [comment]
Please present a PR in the upstream repo first: https://github.com/matomo-org/device-detector

Once it gets merged, feel free to open a new PR with updated regexes here.
