### ISSUE TITLE
Android User Agent requires semicolons when others do not

### ISSUE THREAD

**Issue by swoopej** [podigee/device_detector#34]
curious why `android_tablet_fragment?` and `android_mobile_fragment?` require semicolons and other operating systems (Opera) do not? We [don't use semicolons in our user agent](https://github.com/kickstarter/android-oss/blob/master/app/src/main/java/com/kickstarter/services/interceptors/WebRequestInterceptor.java#L81) at Kickstarter, and as far as I can tell there is no standardization here (please correct me if I'm wrong).  Another example user agent from Facebook has a semicolon after `Android` but not after `Mobile`:

`Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/35.0.0.48.273;]`

going to open a pr making the semicolon optional.

**Comment by yagooar** [comment]
Solved in https://github.com/podigee/device_detector/pull/35
