### ISSUE TITLE
Last regexes and fixtures for device-detector, tests not passing

### ISSUE THREAD

**Issue by rporrasluc** [podigee/device_detector#37]
Hello, due to the number of changes in the device-detector original library, even if I run the rake tasks for updating the YAML files, the tests do not pass.

I have seen that some fixes have been added to the library so that is presumably the reason why the tests do not pass. I tried to change some results expected as "" but returned as nil and vice versa, but I could not get all the tests passed, so I think the best would be to start adding those fixes to this Ruby implementation of the library.

I am willing to contribute, I will start adding some pull requests.

Thanks and congratulations for the excellent library.

**Comment by misner** [comment]
+1 , see https://github.com/podigee/device_detector/issues/39. would love but don't have the level sufficient to help.

**Comment by yagooar** [comment]
Solved in https://github.com/podigee/device_detector/commit/5cdc27c325c12209c5d078900857e91bae7e2433

**Comment by rporrasluc** [comment]
Thanks a lot @yagooar, I can now use your version instead of my forked branch. Really appreciate your work.
