### ISSUE TITLE
Usage from README.md doesn't work

### ISSUE THREAD

**Issue by bencrouse** [podigee/device_detector#4]
This gem seems so promising!

I looked into this for a few minutes, but couldn't determine the problem. Here's what I ran in irb:

```code
2.1.5 :001 > require 'device_detector'
 => true 
2.1.5 :002 > user_agent = 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.17 Safari/537.36'
 => "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.17 Safari/537.36" 
2.1.5 :003 > client = DeviceDetector.new(user_agent)
 => #<DeviceDetector:0x007fab345a3b10 @user_agent="Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.17 Safari/537.36"> 
2.1.5 :004 > client.name
 => "Chrome" 
2.1.5 :005 > client.full_version
 => "30.0.1599.17" 
2.1.5 :006 > client.os_name
 => "Windows" 
2.1.5 :007 > client.os_full_version
 => "8" 
2.1.5 :008 > client.device_name
 => "OW64" 
2.1.5 :009 > client.device_type
 => "tv" 
```

**Comment by peteygao** [comment]
Is the problem the fact that device type is reporting TV? I implemented device type detection by porting over the Regex from a PHP project so it's probably a bad Regex somewhere. I'll look into it later today.

**Comment by bencrouse** [comment]
yeah i assumed that user agent was a desktop chrome. here are the results for my current user agent. it correctly shows Safari 8.0.3 on Yosemite. i'd assume it'd at least have device_type of desktop:

```code
2.1.5 :001 > require 'device_detector'
 => true 
2.1.5 :002 > user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18'
 => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18" 
2.1.5 :003 > client = DeviceDetector.new(user_agent)
 => #<DeviceDetector:0x007f8bd45e30a0 @user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18"> 
2.1.5 :004 > client.name
 => "Safari" 
2.1.5 :005 > client.full_version
 => "8.0.3" 
2.1.5 :006 > client.os_name
 => "Mac" 
2.1.5 :007 > client.os_full_version
 => "10_10_2" 
2.1.5 :008 > client.device_name
 => nil 
2.1.5 :009 > client.device_type
 => nil 
```

**Comment by yagooar** [comment]
@bencrouse 
> i'd assume it'd at least have device_type of desktop


This seems like a valid request. In your example, `os_name` and `device_name` would be `Mac`, and `device_type` would be `desktop`.
If we had a request from a Windows OS, we would have to check the version as well, in order to detect if the device is `desktop`.

In order to achieve this, we would need to have a list of rules for these cases. Also, it would be nice to have a method like `device_known?` if the device can't be detected at all.

**Comment by bencrouse** [comment]
ok, got it, this is a new feature. having nil for my device type makes sense then. so is the chrome example from the readme actually a tv?

**Comment by yagooar** [comment]
No, it's not a TV. It should actually be nil.

I think we have two different issues here: the example being wrong, and missing detection of desktop clients. @peteygao has written he would take a look at the example detection, I will take care of thinking about adding the new feature :)

Thanks for reporting!

**Comment by peteygao** [comment]
I'm having trouble with the term `desktop`. How do I know it's not a laptop, a tablet (e.g. Microsoft Surface) or a netbook (I have one in my office drawer which I never use, but... :stuck_out_tongue:)?

And detecting the actual form factor is impossible from the user agent alone. Perhaps the term `pc` ("personal computer" is an all encompassing term for desktop/laptop/tablets alike) is more appropriate?

And yes, there are 2 problems here. Current false positive, and a expectation of detecting desktop clients.

**Comment by bencrouse** [comment]
thanks so much guys!

**Comment by yagooar** [comment]
@peteygao `personal computer` sounds better and makes more sense. I will use the term, but I prefer to leave it in its full form `personal computer` without abbreviating.

**Comment by skaes** [comment]
The recognition has been fixed in my pull request https://github.com/podigee/device_detector/pull/12.

I have opted to return "desktop" as the device type. This corresponds to what the upstream project does.

Let's not invent new device types. If upstream changes and introduces a new device type conflicting with your choice, you're basically screwed.
