### ISSUE TITLE
Apple Podcasts (app) detected as "Mobile Safari"

### ISSUE THREAD

**Issue by dan** [podigee/device_detector#47]
irb(main):040:0> s = 'AppleCoreMedia/1.0.0.10B500 (iPod; U; CPU OS 6_1_6 like Mac OS X; en_gb)'
=> "AppleCoreMedia/1.0.0.10B500 (iPod; U; CPU OS 6_1_6 like Mac OS X; en_gb)"
irb(main):041:0> DeviceDetector.new(s).name
=> "Mobile Safari"

**Comment by girardof** [comment]
Hi Dan,

Usually, we recommend fixing the upstream definitions first: [https://github.com/matomo-org/device-detector](https://github.com/matomo-org/device-detector)

Once the changes are merged there, we can pull the latest device definitions into this project.

Thanks a lot
