### ISSUE TITLE
missing Smartphone Googlebot

### ISSUE THREAD

**Issue by dimanyc** [podigee/device_detector#5]
Hi,

I noticed that **Smartphone Googlebot** is not listed in `bots.yml`. I think it's an important one to have, given the [latest news about Google's Algorithm update](http://googlewebmastercentral.blogspot.com/2015/02/finding-more-mobile-friendly-search.html), and I  would like to add it to the list.

**Comment by yagooar** [comment]
Would you please provide a user agent sample?

I have tried with the following code that looks fine:

```ruby
[1] pry(main)> user_agent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)'
=> "Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)"
[2] pry(main)> client = DeviceDetector.new(user_agent)
=> #<DeviceDetector:0x007fe5a149e538
 @user_agent=
  "Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)">
[3] pry(main)> client.name
=> "Mobile Safari"
[4] pry(main)> client.bot?
=> true
[5] pry(main)> client.bot_name
=> "Googlebot"
```

I have taken the user agent string from here: http://googlewebmastercentral.blogspot.com.es/2011/12/introducing-smartphone-googlebot-mobile.html so please tell me if I'm wrong.

**Comment by dimanyc** [comment]
Interesting. They must have combined the Mobile and Smartphone bots. Both, however, are still listed as separate crawlers in [Google Webmaster](https://support.google.com/webmasters/answer/1061943?hl=en). Thanks for your help! Closing.
