### ISSUE TITLE
DuckDuckGo Android app registered as Bot

### ISSUE THREAD

**Issue by dkam** [podigee/device_detector#67]
Hi there - this user agent is recognised as a bot: 
"Mozilla/5.0 (Linux; Android 9) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36 DuckDuckGo/5"

But I suspect it is this app: https://github.com/duckduckgo/Android 

I don't have Android to test it unfortunately.

**Comment by spiderpug** [comment]
Hi Dan,

Usually, we recommend fixing the upstream definitions first: https://github.com/matomo-org/device-detector

Once the changes are merged there, we can pull the latest device definitions into this project.

Thanks a lot

**Comment by dkam** [comment]
Looks like it's fixed upstream and your latest merge has it included now.  Thanks!
