### ISSUE TITLE
Google Image Proxy - not a bot?

### ISSUE THREAD

**Issue by scebotari** [podigee/device_detector#72]
As it is stated in this [post](https://www.scientiamobile.com/what-is-google-image-proxy/) Google Image Proxy is not a bot. This acts more like proxy. For us this means, that the click/open is real (performed by real person), but we're not able to detect the real device, because user agent has been overwritten by Google Image Proxy.

Link to the regexp: https://github.com/podigee/device_detector/blob/develop/regexes/bots.yml#L588

**Comment by spiderpug** [comment]
Hi @scebotari ,

Usually, we recommend fixing the upstream definitions first. We use the definitions of the Matomo project. You should discuss the issue there, as the bot regex is likely maintained here: 

https://github.com/matomo-org/device-detector/blob/8722c34c3738ab1c7e1ffe4e1492436371b66ce0/regexes/bots.yml#L612

Once potential changes are merged there, we can pull the latest bot definitions into this project.

Thanks a lot
