### ISSUE TITLE
Use RuboCop?

### ISSUE THREAD

**Issue by utkarsh2102** [podigee/device_detector#74]
Hi @spiderpug,

Thanks for maintaining this so far!
However, there are a bunch of things that could be fixed according to the Ruby style guide.

Would you consider using RuboCop?
I would be happy to raise a PR if so :)

**Comment by spiderpug** [comment]
Thank you for your suggestion.

We use Rubocop internally as well so I added some rules and adjusted the models in https://github.com/podigee/device_detector/commit/fad9de58cae6327cdaeee95eb7c053a954f67886 .

**Comment by utkarsh2102** [comment]
Hi @spiderpug,

Thanks! Could you also update RuboCop to v0.89? I can make a PR too, let me know!
