### ISSUE TITLE
Ruby warnings

### ISSUE THREAD

**Issue by n-rodriguez** [podigee/device_detector#89]
Hi there!

Since release 1.0.6 I get this warning :

```sh
/cache/nicolas/concerto/ruby-master/ruby/3.0.0/gems/device_detector-1.0.6/lib/device_detector/parser.rb:88: warning: regular expression has ']' without escape
/cache/nicolas/concerto/ruby-master/ruby/3.0.0/gems/device_detector-1.0.6/lib/device_detector/parser.rb:88: warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression
```

Thank you!

**Comment by n-rodriguez** [comment]
This PR https://github.com/podigee/device_detector/pull/88 should help to reveal the warning.

**Comment by Maarius** [comment]
I wanted to file the same issue. Glad to see that it was already created.

**Comment by yakschuss** [comment]
Whoops, looks like I doubled up [here](https://github.com/podigee/device_detector/issues/91)

**Comment by marcelgo** [comment]
Thanks everybody for keeping track and all your efforts. We will provide a newer version of the gem soon.
