### ISSUE TITLE
Old TV not recognised

### ISSUE THREAD

**Issue by batiste** [podigee/device_detector#9]
This user agent OS and device name is not recognised

SAMSUNG-GT-E2152/E2152XXJK2 NetFront/3.5 Profile/MIDP-2.0 Configuration/CLDC-1.1

**Comment by yagooar** [comment]
Thanks for opening the issue, could you please provide the expected values for the following methods: `#name, #full_version, #os_name, #os_full_version, #device_name, #device_type`?

**Comment by batiste** [comment]
It seems to be this phone... Not really a TV:

http://www.gsmarena.com/samsung_e2152-3448.php

**Comment by batiste** [comment]
I would think it safe to assume that any device that use NetFront is a "handheld" device as a first approximation.

**Comment by batiste** [comment]
os_name: Samsung OS
device_name:  Samsung E2152
device_type: handheld
os_full_version: ?
full_version: ?

**Comment by yagooar** [comment]
According to the information found on this website: http://myip.ms/view/comp_os/1157/Samsung_GT_E2152.html, I would add a detection rule that will comply with the following spec:

```ruby
client.name.must_equal 'NetFront 3.5'
client.full_version.must_equal '3.5'
client.os_name.must_equal 'Samsung GT-E2152'
client.os_full_version.must_equal 'GT-E2152'
client.device_name.must_equal 'Samsung GT-E2152'
client.device_type.must_equal 'feature phone'
```

**Comment by skaes** [comment]
This is fixed in my pull request https://github.com/podigee/device_detector/pull/12
