### ISSUE TITLE
browser is said to be mobile safari when using an app on an iPad

### ISSUE THREAD

**Issue by PatriciaHudakova** [podigee/device_detector#96]
When using an app on an iOS, the browser is set correctly, however once the OS in the user agent changes to iPadOS, then the browser is set to be recognised as a mobile safari even though the app is still being used.

e.g.
`<app_name>/3.7.1 (iPad; iPadOS 15.6.1; Scale/2.00)/ DeviceId/48C8426D-64B6-4961-BD3E-09FD99C3B046/ BuildNumber/1111` returns browser as "Mobile Safari" but
`<app_name>/3.7.1 (iPad; iOS 15.6.1; Scale/2.00)/ DeviceId/48C8426D-64B6-4961-BD3E-09FD99C3B046/ BuildNumber/1111` returns browser as "<app_name>"

Similar thing happens with android where the browser on an android device returns "Android Browser" even though the app name is specified

At the moment I have a hack in place that checks for the app name at the beginning of the user agent string but that is just a hack and I would prefer not to make use of it for long. I'll tinker with this library if I have some time, just thought I would report this issue 🥺

**Comment by liviuconcioiu** [comment]
@PatriciaHudakova can you report the user agents that aren't correctly detected to https://github.com/matomo-org/device-detector? Those have to be solved upstream. You can always check if the detection is correct here: [https://devicedetector.lw1.at/](https://devicedetector.lw1.at/)

**Comment by girardof** [comment]
Thanks @PatriciaHudakova and @liviuconcioiu for your comments.
This issue was fixed in https://github.com/matomo-org/device-detector and now imported in this gem, it's available in the v1.1.1.
